### ISSUE TITLE
xcode 9 iOS11 GzipSwift/zlib/module.modulemap:1:8: note: previously defined here module zlib [system] 

### ISSUE THREAD

**Issue by quanliangswift** [1024jp/GzipSwift#19] opened 2017-09-25 11:47 UTC
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/module.modulemap:1872:8: error: redefinition of module 'zlib'
module zlib [system] [extern_c] {
       ^
/Pods/GzipSwift/zlib/module.modulemap:1:8: note: previously defined here
module zlib [system]

**Comment by 1024jp** [comment] 2017-09-25 14:52
Please try the latest GzipSwift 4.0.
ref. #14

**Comment by krze** [comment] 2017-09-26 16:01
I'm having this issue as well, even with GzipSwift 4.0. I can reproduce this issue with xcode and with this swift package:

https://github.com/krze/GzipIssue

1. Check out this repo
2. Run `swift build -c release`
3. Note the errors for the redeclaration of zlib

The issue is fixed if you remove zlib from `Package.resolved`

**Comment by 1024jp** [comment] 2017-09-28 04:27
Aha, sorry, I forgot about SPM + Apple devices. I have to update Package.swift somehow...

**Comment by danramteke** [comment] 2017-11-07 20:48
@krze @1024jp checkout my fork here https://github.com/danramteke/GzipSwift which fixes this problem using Swift Package Manager on Mac and Linux.

**Comment by 1024jp** [comment] 2017-11-11 06:07
I suppose this issue was fixed on GzipSwift 4.0.3, which I've just released, thanks to #23.
Please tell me if the matter still exists.

**Closed by 1024jp** 2017-11-11 06:07 UTC
